name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Get Pages url
        id: pages
        uses: actions/configure-pages@v2
        with:
          enablement: false

      - name: Build live version of site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path || '' }}"

      - name: Fix Mermaid diagrams in HTML
        run: |
          find ."${{ steps.pages.outputs.base_path || '' }}" -name "*.html" -type f -exec sed -i 's/<pre><code class="language-mermaid">/<pre class="mermaid">/g' {} \;
          find ."${{ steps.pages.outputs.base_path || '' }}" -name "*.html" -type f -exec sed -i 's/<\/code><\/pre>/<\/pre>/g' {} \;

      